# Generated by Django 5.1.3 on 2024-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_employeeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='employee',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(default='No content'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
