# Generated by Django 5.1.3 on 2024-12-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_notification_employee_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employee'),
        ),
        migrations.AlterField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employee'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
