# Generated by Django 5.1.3 on 2024-12-02 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_session_employeesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='date',

        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.AddField(
            model_name='session',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='assigned_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=255, default='Default Session Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmployeeSession',
        ),
    ]
