# Generated by Django 5.1.3 on 2024-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_onboardingsession_sessionassignment_delete_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionassignment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionassignment',
            name='employee',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('assigned_employees', models.ManyToManyField(related_name='assigned_sessions', to='adminapp.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='OnboardingSession',
        ),
        migrations.DeleteModel(
            name='SessionAssignment',
        ),
    ]
