# Generated by Django 5.1.3 on 2024-12-03 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_remove_sessionassignment_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('employees', models.ManyToManyField(related_name='training_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
